CREATE TABLE MENSAJES(
  IDMSG NUMBER NOT NULL,
	TIPO NUMBER,
	ID NUMBER,
	DIA TIMESTAMP (6),
	FECHA TIMESTAMP (6),
	TEXTO NCLOB,
	USER_ VARCHAR2(250),
	IP VARCHAR2(15)
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX MENSAJES_PK ON MENSAJES (IDMSG) TABLESPACE TS_NETTIME_I;

ALTER TABLE MENSAJES ADD CONSTRAINT MENSAJES_PK PRIMARY KEY (IDMSG) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;

CREATE INDEX MENSAJES_TIPO ON MENSAJES (TIPO) TABLESPACE TS_NETTIME_I;
