CREATE TABLE NOTIFICACIONES(
  ID NUMBER NOT NULL, 
	TIPO NUMBER NOT NULL, 
	FINALIZADA NUMBER(1,0) DEFAULT 0 NOT NULL, 
	TEXTO NCLOB, 
	CREACION TIMESTAMP (6) DEFAULT SYSDATE NOT NULL, 
	FIN TIMESTAMP (6), 
	IDPER NUMBER, 
	FECHA TIMESTAMP (6)
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX NOTIFICACIONES_PK ON NOTIFICACIONES (ID) TABLESPACE TS_NETTIME_I;

ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOTIFICACIONES_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;

CREATE INDEX NOTIFICACIONES_TIPOIDPERFECHA ON NOTIFICACIONES (TIPO, IDPER, FECHA) TABLESPACE TS_NETTIME_I;
