GRANT EXECUTE ON nettimeadm.OBTENERMARCAJESXPERSONAYFEC_V2 TO nettimeusr;
CREATE SYNONYM nettimeusr.OBTENERMARCAJESXPERSONAYFEC_V2 FOR nettimeadm.OBTENERMARCAJESXPERSONAYFEC_V2;

GRANT EXECUTE ON nettimeadm.OBTENERDIASXPERSONAXFECHA_V2 TO nettimeusr;
CREATE SYNONYM nettimeusr.OBTENERDIASXPERSONAXFECHA_V2 FOR nettimeadm.OBTENERDIASXPERSONAXFECHA_V2;


GRANT EXECUTE ON nettimeadm.GUARDARDIA_V2 TO nettimeusr;
CREATE SYNONYM nettimeusr.GUARDARDIA_V2 FOR nettimeadm.GUARDARDIA_V2;

GRANT EXECUTE ON nettimeadm.ELIMINARMARCAJESXPERSONAYFECH2 TO nettimeusr;
CREATE SYNONYM nettimeusr.ELIMINARMARCAJESXPERSONAYFECH2 FOR nettimeadm.ELIMINARMARCAJESXPERSONAYFECH2;
