CREATE TABLE APPDATA(
	IDTYPE	NUMBER NOT NULL,
	IDELEM	NUMBER NOT NULL,
	NAME		VARCHAR2(200),
	DATA		BLOB
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX APPDATA_PK ON APPDATA (
	IDTYPE,
	IDELEM
) TABLESPACE TS_NETTIME_I;

ALTER TABLE APPDATA ADD CONSTRAINT APPDATA_PK PRIMARY KEY (IDTYPE, IDELEM) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;
