CREATE TABLE DIAS(
	IDDIA NUMBER NOT NULL,
	IDPER NUMBER NOT NULL,
	FECHA TIMESTAMP (6) NOT NULL,
	IDJOR NUMBER,
	TM NUMBER,
	IDANO NUMBER,
	VALORES BLOB,
	MINFIN NUMBER DEFAULT (-1),
	DragTT NUMBER NULL,
	DaysTT NUMBER NULL,
	DragWA NUMBER NULL,
	DaysWA NUMBER NULL,
	DragWO NUMBER NULL,
	DaysWO NUMBER NULL
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX DIAS_PK ON DIAS (IDDIA) TABLESPACE TS_NETTIME_I;

ALTER TABLE DIAS ADD CONSTRAINT DIAS_PK PRIMARY KEY (IDDIA) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;

CREATE INDEX DIAS_IDPER ON DIAS (IDPER) TABLESPACE TS_NETTIME_I;

CREATE UNIQUE INDEX DIAS_IDPERFECHA ON DIAS (IDPER, FECHA) TABLESPACE TS_NETTIME_I;

