CREATE TABLE NMARCAJES(
	IDMAR NUMBER NOT NULL,
	IDPER NUMBER NOT NULL,
	IDINC NUMBER,
	IDTER NUMBER,
	IDLEC NUMBER,
	FECHA TIMESTAMP (6) NOT NULL,
	ORIGEN NUMBER,
	TIPO NUMBER,
	ESTADO NUMBER,
	TAR VARCHAR2(50),
	IP VARCHAR2(15),
	USUARIO VARCHAR2(250),
	ACCESO CHAR(1),
	LAT DECIMAL,
	LON DECIMAL,
	MOBILEID VARCHAR(100),
	CRC NUMBER
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX NMARCAJES_PK ON NMARCAJES (
	IDMAR
) TABLESPACE TS_NETTIME_I;

CREATE INDEX NMARCAJES_IDPER_FECHA ON NMARCAJES (IDPER, FECHA) TABLESPACE TS_NETTIME_I;

ALTER TABLE NMARCAJES ADD CONSTRAINT NMARCAJES_PK PRIMARY KEY (IDMAR) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;
