CREATE TABLE PerfilesAccesos (
	ID NUMBER NOT NULL,
	IDPERFIL NUMBER NOT NULL,
	ANO NUMBER NOT NULL,
	IDLEC NUMBER NULL,
	FRANJASDIA BLOB NOT NULL) TABLESPACE TS_NETTIME_D;
/

CREATE UNIQUE INDEX PERFILESACCESOS_PK ON PerfilesAccesos (ID) TABLESPACE TS_NETTIME_I;
/

ALTER TABLE PerfilesAccesos ADD CONSTRAINT PERFILESACCESOS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;
/

create sequence IDPASEQ minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
/

CREATE OR REPLACE PROCEDURE ResetIDPASEQ AS

cval   INTEGER;
inc_by VARCHAR2(25);
startvalue integer;

BEGIN
  SELECT NVL(MAX(ID), 0)+1 INTO startvalue FROM PerfilesAccesos;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE IDPASEQ MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT IDPASEQ.NEXTVAL FROM dual' INTO cval;

  cval := cval - startvalue + 1;
  IF cval < 0 THEN
    inc_by := ' INCREMENT BY ';
    cval:= ABS(cval);
  ELSE
    inc_by := ' INCREMENT BY -';
  END IF;
   
  EXECUTE IMMEDIATE 'ALTER SEQUENCE IDPASEQ ' || inc_by || cval;
  EXECUTE IMMEDIATE 'SELECT IDPASEQ.NEXTVAL FROM dual' INTO cval;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE IDPASEQ INCREMENT BY 1';

END;
/

CREATE OR REPLACE PROCEDURE GuardaPerfilAccesos(paramIDPERFIL IN int DEFAULT NULL,
																							paramANO IN int DEFAULT NULL,
																							paramIDLEC IN int DEFAULT NULL,
																							paramFRANJASDIA IN blob DEFAULT NULL) AS
BEGIN

merge into PerfilesAccesos using dual on (IDPERFIL = paramIDPERFIL and ANO = paramANO and IDLEC = paramIDLEC)
 when not matched then INSERT (ID, IDPERFIL, ANO, IDLEC, FRANJASDIA) VALUES (IDPASEQ.nextval, paramIDPERFIL, paramANO, paramIDLEC, paramFRANJASDIA)
     when matched then UPDATE SET FRANJASDIA = paramFRANJASDIA;
END;
/

CREATE OR REPLACE PROCEDURE DamePerfilAccesos(paramIDPERFIL  IN int, paramANO  IN int, paramIDLEC  IN int, RCT1 IN OUT GLOBALPKG.RCT1) AS
BEGIN
	IF paramANO < 0 AND paramIDLEC < 0 THEN
		OPEN RCT1 FOR SELECT * FROM PerfilesAccesos WHERE IDPERFIL = paramIDPERFIL;
  ELSIF  paramANO < 0 THEN
		OPEN RCT1 FOR SELECT * FROM PerfilesAccesos WHERE IDPERFIL = paramIDPERFIL AND IDLEC = paramIDLEC;
  ELSIF paramIDLEC < 0 THEN
		OPEN RCT1 FOR SELECT * FROM PerfilesAccesos WHERE IDPERFIL = paramIDPERFIL AND ANO = paramANO;
  ELSE
		OPEN RCT1 FOR SELECT * FROM PerfilesAccesos WHERE IDPERFIL = paramIDPERFIL AND ANO = paramANO AND IDLEC = paramIDLEC;
  END IF;
END;
/
