CREATE TABLE Sessions(
  ID NUMBER NOT NULL,
	UNAME VARCHAR2(200) NOT NULL,
	IP VARCHAR2(50) NOT NULL,
	AuthType VARCHAR2(50),
	START_ TIMESTAMP (6),
	END TIMESTAMP (6)
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX SESSIONS_PK ON Sessions (ID) TABLESPACE TS_NETTIME_I;

ALTER TABLE Sessions ADD CONSTRAINT SESSIONS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;

CREATE INDEX SESSIONS_USER ON Sessions (UNAME) TABLESPACE TS_NETTIME_I;



CREATE TABLE SessionDetail(
	ID NUMBER NOT NULL,
	IDSES NUMBER NOT NULL,
	TS TIMESTAMP NOT NULL,
	URL VARCHAR2(1024),
	DATA BLOB
) TABLESPACE TS_NETTIME_D;

CREATE UNIQUE INDEX SESSIONDETAIL_PK ON SessionDetail (ID) TABLESPACE TS_NETTIME_I;

ALTER TABLE SessionDetail ADD CONSTRAINT SESSIONDETAIL_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_NETTIME_I ENABLE;

CREATE INDEX SESSIONDETAIL_IDSES ON SessionDetail (IDSES) TABLESPACE TS_NETTIME_I;
